version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

  caddy:
    image: caddy:2
    ports:
      - 80:80
    volumes:
      - ./caddy/Caddyfile.json:/etc/caddy/Caddyfile.json
    command: caddy run --config /etc/caddy/Caddyfile.json
